### ISSUE TITLE
Version 3.0 break an important part of the contract where we can set the Timeout for waiting for lock

### ISSUE THREAD

**Issue by Belphemur** [amoerie/keyed-semaphores#23]
Hello,

In version 3.0, we can't set the timeout for the lock.

This seems like nothing since there is a cancellationToken but the underlying semaphore have a fail fast case when the timeout = 0 to return directly if it can't take the lock.

Also, having to use a CancellationTokenSource to be able to set a proper timeout isn't the best contract either.

**Comment by amoerie** [comment]
Looking closer into this, this timeout parameter is troublesome.

This signature specifically:

`Task<IDisposable> WaitAsync(TKey key, TimeSpan timeout)`

You see, `SemaphoreSlim.WaitAsync` returns a boolean whether the acquisition was succesful or not within the timeout.
But we have to return an IDisposable so that the number of consumers of a keyed semaphore can be decremented.

I think the only two options we have are
1. Allow a timeout parameter and throw an OperationCanceledException when the timeout expires (i.e. when SemaphoreSlim.Wait returns false
2. Do not provide a timeout parameter at all (i.e. revert your pull request)

I'm interested in your opinion @Belphemur

**Comment by Belphemur** [comment]
I'm running different scenarios and I don't see how the timeout cause an issue in the current implementation.

I actually see an issue with the lack of handling of `OperationCancelledException`.

# Reasoning
* `Provide` increment the number of consumer of the Lock
* `keyedSemaphore.Releaser` is the Disposable that take care of "releasing the lock"
* When you get a `OperationCancelledException` you get in a state where the lock "isn't used anymore" but the releaser code won't be called. So you end up with too many consumers on the lock.

**Comment by amoerie** [comment]
How would someone calling LockAsync know that the timeout expired, and it is therefore not safe to proceed with code that needs to be executed within a locked semaphore?

I do agree that you might have found an issue with regards to missing OperationCanceledException handling. I'll look into this first thing tomorrow.

**Comment by Belphemur** [comment]
Ohh I see your point, sorry I missed it first.
Since people don't have access to the wait method, they can't know the difference between timeout expired, and actually getting the lock.

In that case, I'd suggest adding a new Exception specifically for that use case. `TimeoutException(Timeout reached of XXX without getting the lock)`. I can add that to my other PR.

**Comment by amoerie** [comment]
I disagree that throwing an exception should be used for what is probably not a very exceptional use case.
Instead of using exceptions, I adapted the API to be called _TryLock_ that returns a boolean.  You can pass a callback parameter that will only be invoked within a locked keyed semaphore. See the README for examples.
