### ISSUE TITLE
Nested locking

### ISSUE THREAD

**Issue by pvrobays** [amoerie/keyed-semaphores#62]
Right now nested locking could result in a deadlock because the underlying hash codes of both keys could collide.

e.g.: 
```
using (await KeyedSemaphore.LockAsync("ABC", cancellationToken))
{
    // ...
    using (await KeyedSemaphore.LockAsync("XYZ", cancellationToken)) { // <-- here we may deadlock
        // ....
    }
    // ....
}
```

So in case the hash codes of "ABC" and "XYZ" match to the same indexer for the semaphore locks, the code will deadlock while trying to retrieve the 2nd.

**Comment by amoerie** [comment]
Unfortunately this is just a mirror of how SemaphoreSlim works. With traditional locking, this works because the thread id is stored in the header of the object being locked, and .NET can detect the current thread already holds that lock and let it pass.
SemaphoreSlim does not provide such a mechanism, and instead will deadlock (if the CurrentCount is 0 of course)

I've experimented with using AsyncLocal to avoid a deadlock within a single call stack, but even then you could have deadlocks between two separate threads. On top of that, AsyncLocal has a negative performance impact.

If you need to have nested locking, the only solution is to use separate instances of `KeyedSemaphoreCollection` so they cannot share the same underlying SemaphoreSlim, or to not use keyed semaphores at all, and solve your problem in a different way.

**Comment by pvrobays** [comment]
Thanks. I agree implementing support for nested locks would make for a less performant and more complex solution.
It might be opportune to add a disclaimer in the readme that nested locking isn't supported and can lead to deadlocks?

**Comment by amoerie** [comment]
I've added a section about nested locks to the README. It is a considerable footgun indeed.
